export enum AppliedJobErrorType {
    APPLIED_JOB_NOT_FOUND = 'APPLIED_JOB_NOT_FOUND',
    ALREADY_APPLIED = 'ALREADY_APPLIED',
    NOT_ALLOWED_UPDATE_APPLICATION_APPROVED_OR_DENIED = 'NOT_ALLOWED_UPDATE_APPLICATION_APPROVED_OR_DENIED',
    NOT_ALLOWED_UPDATE_APPLICATION_STATUS = 'NOT_ALLOWED_UPDATE_APPLICATION_STATUS',
}
