export enum AuthErrorType {
    USER_NOT_FOUND = 'USER_NOT_FOUND',
    INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
    ACCOUNT_BLOCKED = 'ACCOUNT_BLOCKED',
    ACCOUNT_PENDING = 'ACCOUNT_PENDING',
    ACCOUNT_INACTIVE = 'ACCOUNT_INACTIVE',
    TOKEN_EXPIRED = 'TOKEN_EXPIRED',
    TOKEN_INVALID = 'TOKEN_INVALID',
    AUTH_FAILED = 'AUTH_FAILED',
    REFRESH_TOKEN_EXPIRED = 'REFRESH_TOKEN_EXPIRED',
    REFRESH_TOKEN_INVALID = 'REFRESH_TOKEN_INVALID',
}
