export enum AuthErrorType {
    USER_NOT_FOUND = 'USER_NOT_FOUND',
    INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
    ACCOUNT_BLOCKED = 'ACCOUNT_BLOCKED',
    ACCOUNT_PENDING = 'ACCOUNT_PENDING',
    ACCOUNT_INACTIVE = 'ACCOUNT_INACTIVE',
    TOKEN_EXPIRED = 'TOKEN_EXPIRED',
    TOKEN_INVALID = 'TOKEN_INVALID',
    AUTH_FAILED = 'AUTH_FAILED',
    REFRESH_TOKEN_EXPIRED = 'REFRESH_TOKEN_EXPIRED',
    REFRESH_TOKEN_INVALID = 'REFRESH_TOKEN_INVALID',
    EMAIL_ALREADY_EXISTS = 'EMAIL_ALREADY_EXISTS',
    EMAIL_NOT_EXISTS = 'EMAIL_NOT_EXISTS',
    USER_NOT_ACTIVE = 'USER_NOT_ACTIVE',
    NOT_ALLOW_RESET_PW = 'NOT_ALLOW_RESET_PW',
}

export enum OAuth2ErrorType {
    FACEBOOK_EMAIL_REQUIRED = 'FACEBOOK_EMAIL_REQUIRED',
    AUTH_TOKEN_EXPIRED = 'AUTH_TOKEN_EXPIRED',
}
