export enum CategoryErrorType {
    CATEGORY_NOT_FOUND = 'CATEGORY_NOT_FOUND',
    PARENT_CATEGORY_NOT_FOUND = 'PARENT_CATEGORY_NOT_FOUND',
    CANNOT_BE_OWN_PARENT = 'CANNOT_BE_OWN_PARENT',
    CATEGORY_MAY_BE_IN_USE = 'CATEGORY_MAY_BE_IN_USE',
}
