export enum CreateJobWishListErrorType {
    REQUIRED_JOB_ID = 'REQUIRED_JOB_ID',
    STRING_JOB_ID = 'JOB_ID_STRING',
}

export enum UpdatePersonalProfileDtoErrorType {
    PROFILE_URL_REQUIRED = 'PROFILE_URL_REQUIRED',
    INVALID_PROFILE_URL = 'INVALID_PROFILE_URL',
    PAGE_URL_REQUIRED = 'PAGE_URL_REQUIRED',
    INVALID_PAGE_URL = 'INVALID_PAGE_URL',
    FULL_NAME_REQUIRED = 'FULL_NAME_REQUIRED',
    PHONE_NUMBER_INVALID = 'PHONE_NUMBER_INVALID',
}

export enum UpdateCandidateProfileDtoErrorType {
    GENDER_REQUIRED = 'GENDER_REQUIRED',
}

export enum UpdateCompanyInfoDtoErrorType {
    LOGO_URL_REQUIRED = 'LOGO_URL_REQUIRED',
    INVALID_LOGO_URL = 'INVALID_LOGO_URL',
    BACKGROUND_IMAGE_REQUIRED = 'BACKGROUND_IMAGE_REQUIRED',
    INVALID_BACKGROUND_IMAGE = 'INVALID_BACKGROUND_IMAGE',
    NAME_REQUIRED = 'NAME_REQUIRED',
    INVALID_NAME = 'INVALID_NAME',
    BIO_REQUIRED = 'BIO_REQUIRED',
    INVALID_BIO = 'INVALID_BIO',
    PHONE_NUMBER_INVALID = UpdatePersonalProfileDtoErrorType.PHONE_NUMBER_INVALID,
}

export enum UpdateFoundingInfoDtoErrorType {
    INVALID_DESCRIPTION = 'INVALID_DESCRIPTION',
    INVALID_ENTERPRISE_BENEFITS = 'INVALID_ENTERPRISE_BENEFITS',
    INVALID_COMPANY_VISION = 'INVALID_COMPANY_VISION',
    FOUNDED_IN_REQUIRED = 'FOUNDED_IN_REQUIRED',
    INVALID_FOUNDED_IN = 'INVALID_FOUNDED_IN',
    INVALID_ORGANIZATION_TYPE = 'INVALID_ORGANIZATION_TYPE',
    INVALID_TEAM_SIZE = 'INVALID_TEAM_SIZE',
    INDUSTRY_TYPE_REQUIRED = 'INDUSTRY_TYPE_REQUIRED',
    INVALID_INDUSTRY_TYPE = 'INVALID_INDUSTRY_TYPE',
    INVALID_BIO = 'INVALID_BIO',
}

export enum OAuth2LoginErrorType {
    PROVIDER_REQUIRED = 'PROVIDER_REQUIRED',
    PROVIDER_NOT_STRING = 'PROVIDER_NOT_STRING',
    PROVIDER_ID_REQUIRED = 'PROVIDER_ID_REQUIRED',
    PROVIDER_ID_NOT_STRING = 'PROVIDER_ID_NOT_STRING',
    NAME_REQUIRED = 'NAME_REQUIRED',
    NAME_NOT_STRING = 'NAME_NOT_STRING',
    EMAIL_REQUIRED = 'EMAIL_REQUIRED',
    EMAIL_INVALID = 'EMAIL_INVALID',
    PHOTO_REQUIRED = 'PHOTO_REQUIRED',
    PHOTO_NOT_URL = 'PHOTO_NOT_URL',
    ACCESS_TOKEN_REQUIRED = 'ACCESS_TOKEN_REQUIRED',
    ACCESS_TOKEN_NOT_STRING = 'ACCESS_TOKEN_NOT_STRING',
}

export enum QueryPresignedUrlDtoErrorType {
    IS_PUBLISHED_REQUIRED = 'IS_PUBLISHED_REQUIRED',
    IS_PUBLISHED_NOT_BOOLEAN = 'IS_PUBLISHED_NOT_BOOLEAN',
    FILENAME_REQUIRED = 'FILENAME_REQUIRED',
    FILENAME_NOT_STRING = 'FILENAME_NOT_STRING',
    CONTENT_TYPE_REQUIRED = 'CONTENT_TYPE_REQUIRED',
    CONTENT_TYPE_NOT_STRING = 'CONTENT_TYPE_NOT_STRING',
}

export enum CreateCvErrorType {
    CV_URL_REQUIRED = 'CV_URL_REQUIRED',
    CV_URL_NOT_STRING = 'CV_URL_NOT_STRING',
    CV_NAME_REQUIRED = 'CV_NAME_REQUIRED',
    CV_NAME_NOT_STRING = 'CV_NAME_NOT_STRING',
    IS_PUBLISHED_REQUIRED = 'IS_PUBLISHED_REQUIRED',
    IS_PUBLISHED_NOT_BOOLEAN = 'IS_PUBLISHED_NOT_BOOLEAN',
    SIZE_NOT_NUMBER = 'SIZE_NOT_NUMBER',
    SIZE_REQUIRED = 'SIZE_REQUIRED',
}
