export enum CreateJobWishListErrorType {
    REQUIRED_JOB_ID = 'REQUIRED_JOB_ID',
    STRING_JOB_ID = 'JOB_ID_STRING',
}

export enum UpdatePersonalProfileDtoErrorType {
    PROFILE_URL_REQUIRED = 'PROFILE_URL_REQUIRED',
    INVALID_PROFILE_URL = 'INVALID_PROFILE_URL',
    PAGE_URL_REQUIRED = 'PAGE_URL_REQUIRED',
    INVALID_PAGE_URL = 'INVALID_PAGE_URL',
    FULL_NAME_REQUIRED = 'FULL_NAME_REQUIRED',
    PHONE_NUMBER_INVALID = 'PHONE_NUMBER_INVALID',
}

export enum UpdateCandidateProfileDtoErrorType {
    GENDER_REQUIRED = 'GENDER_REQUIRED',
}

export enum UpdateCompanyInfoDtoErrorType {
    LOGO_URL_REQUIRED = 'LOGO_URL_REQUIRED',
    INVALID_LOGO_URL = 'INVALID_LOGO_URL',
    BACKGROUND_IMAGE_REQUIRED = 'BACKGROUND_IMAGE_REQUIRED',
    INVALID_BACKGROUND_IMAGE = 'INVALID_BACKGROUND_IMAGE',
    NAME_REQUIRED = 'NAME_REQUIRED',
    INVALID_NAME = 'INVALID_NAME',
    BIO_REQUIRED = 'BIO_REQUIRED',
    INVALID_BIO = 'INVALID_BIO',
    PHONE_NUMBER_INVALID = UpdatePersonalProfileDtoErrorType.PHONE_NUMBER_INVALID,
}

export enum UpdateFoundingInfoDtoErrorType {
    INVALID_DESCRIPTION = 'INVALID_DESCRIPTION',
    INVALID_ENTERPRISE_BENEFITS = 'INVALID_ENTERPRISE_BENEFITS',
    INVALID_COMPANY_VISION = 'INVALID_COMPANY_VISION',
    FOUNDED_IN_REQUIRED = 'FOUNDED_IN_REQUIRED',
    INVALID_FOUNDED_IN = 'INVALID_FOUNDED_IN',
    INVALID_ORGANIZATION_TYPE = 'INVALID_ORGANIZATION_TYPE',
    INVALID_TEAM_SIZE = 'INVALID_TEAM_SIZE',
    INDUSTRY_TYPE_REQUIRED = 'INDUSTRY_TYPE_REQUIRED',
    INVALID_INDUSTRY_TYPE = 'INVALID_INDUSTRY_TYPE',
}
