export enum CreateJobWishListErrorType {
    REQUIRED_JOB_ID = 'REQUIRED_JOB_ID',
    STRING_JOB_ID = 'JOB_ID_STRING',
}

export enum UpdatePersonalProfileDtoErrorType {
    PROFILE_URL_REQUIRED = 'PROFILE_URL_REQUIRED',
    INVALID_PROFILE_URL = 'INVALID_PROFILE_URL',
    PAGE_URL_REQUIRED = 'PAGE_URL_REQUIRED',
    INVALID_PAGE_URL = 'INVALID_PAGE_URL',
    FULL_NAME_REQUIRED = 'FULL_NAME_REQUIRED',
    PHONE_NUMBER_INVALID = 'PHONE_NUMBER_INVALID',
}

export enum UpdateCandidateProfileDtoErrorType {
    GENDER_REQUIRED = 'GENDER_REQUIRED',
}
