export enum EnterpriseErrorType {
    ENTERPRISE_ALREADY_EXISTS = 'ENTERPRISE_ALREADY_EXISTS',
    ENTERPRISE_CAN_REGISTER = 'ENTERPRISE CAN REGISTER',
    ENTERPRISE_NOT_FOUND = 'ENTERPRISE NOT FOUND',
    ENTERPRISE_NOT_PERMITTION = 'ENTERPRISE NOT PERMITT',
    CANDIDATE_ADDED_WISHLIST = 'CANDIDATE_ADDED_WISHLIST',
    CANDIDATE_NOT_IN_WISHLIST = 'CANDIDATE_NOT_IN_WISHLIST',
    ENTERPRISE_ADDRESS_NOT_FOUND = 'ENTERPRISE_ADDRESS_NOT_FOUND',
}
