export enum EnterpriseErrorType {
    ENTERPRISE_ALREADY_EXISTS = 'ENTERPRISE_ALREADY_EXISTS',
    ENTERPRISE_CAN_REGISTER = 'ENTERPRISE CAN REGISTER',
    ENTERPRISE_NOT_FOUND = 'ENTERPRISE NOT FOUND',
    ENTERPRISE_NOT_PERMITTION = 'ENTERPRISE NOT PERMITT',
}
