export enum JobErrorType {
    JOB_NOT_FOUND = 'JOB_NOT_FOUND',
    JOB_ALREADY_EXISTS = 'JOB_ALREADY_EXISTS',
    JOB_INVALID_CREDENTIALS = 'JOB_INVALID_CREDENTIALS',
    FETCH_JOB_FAILED = 'FETCH_JOB_FAILED',
    JOB_ADDED_WISHLIST = 'JOB_ADDED_WISHLIST',
    JOB_SPECIALIZATION = 'JOB_SPECIALIZATION',
    INVALID_ENTERPRISE = 'INVALID_ENTERPRISE',
    JOB_CATEGORY_JUST_ONE = 'JOB_CATEGORY_JUST_ONE',
    JOB_HAS_APPLICATION = 'JOB_HAS_APPLICATION',
}
