export enum JobErrorType {
    JOB_NOT_FOUND = 'JOB_NOT_FOUND',
    JOB_ALREADY_EXISTS = 'JOB_ALREADY_EXISTS',
    JOB_INVALID_CREDENTIALS = 'JOB_INVALID_CREDENTIALS',
    FETCH_JOB_FAILED = 'FETCH_JOB_FAILED',
}
