export enum UserErrorType {
    USER_NOT_FOUND = 'USER_NOT_FOUND',
    USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS',
    USER_INVALID_CREDENTIALS = 'USER_INVALID_CREDENTIALS',
    FETCH_USER_FAILED = 'FETCH_USER_FAILED',
    FILL_INDUSTRY_BEFORE_MAJORITY = 'FILL_INDUSTRY_BEFORE_MAJORITY',
    MAJORITY_MUST_BE_CHILD_OF_INDUSTRY = 'MAJORITY_MUST_BE_CHILD_OF_INDUSTRY',
    INVALID_PROFILE_ID = 'INVALID_PROFILE_ID',
}
