export enum UserErrorType {
    USER_NOT_FOUND = 'USER_NOT_FOUND',
    USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS',
    USER_INVALID_CREDENTIALS = 'USER_INVALID_CREDENTIALS',
    FETCH_USER_FAILED = 'FETCH_USER_FAILED',
}
