version: '3.8'

services:
  cache:
    container_name: redis_cache
    image: redis:6.2-alpine
    restart: always
    ports:
      - '${REDIS_PORT}:6379'
    command: >
      redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD} 
      --user ${REDIS_USER} on >${REDIS_PASSWORD} ~* +@all
    volumes: 
      - cache:/data

  boilerplate_db:
    container_name: boilerplate_db
    image: postgres:12.3-alpine
    environment:
      - POSTGRES_PASSWORD=${TYPEORM_PASSWORD}
      - POSTGRES_USER=${TYPEORM_USERNAME}
      - POSTGRES_DB=${TYPEORM_DATABASE}
      - PG_DATA=/var/lib/postgresql/data
    ports:
      - ${TYPEORM_PORT}:5432
    volumes:
      - pgdata:/var/lib/postgresql/data


volumes:
  cache:
  pgdata:
