version: '3.8'

services:
  api:
    container_name: api-job-compass
    build:
      context: .
      dockerfile: Dockerfile
    command: pnpm run start:dev
    depends_on:
      - boilerplate_db
      - redis
    env_file:
      - .env
    ports:
      - '3001:3001'
    volumes:
      - .:/app
      - /app/node_modules

  redis:
    container_name: redis_cache
    image: redis:latest
    restart: always
    env_file:
      - .env
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - '${REDIS_PORT}:6379'
    volumes:
      - redis_data:/data

  boilerplate_db:
    container_name: boilerplate_db
    image: postgres:12.3-alpine
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${TYPEORM_USERNAME}
      - POSTGRES_PASSWORD=${TYPEORM_PASSWORD}
      - POSTGRES_DB=${TYPEORM_DATABASE}
      - PG_DATA=/var/lib/postgresql/data
    ports:
      - '${TYPEORM_PORT}:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  redis_data:
    driver: local
  pgdata:
    driver: local
