name: Build and Deploy API Backend to Azure

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image for API
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/jobcompass-api:latest .

      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/jobcompass-api:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy API Backend to Server
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            sudo docker stop jobcompass-api || true
            sudo docker rm jobcompass-api || true
            sudo docker rmi ${{ secrets.DOCKER_USERNAME }}/jobcompass-api:latest || true
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/jobcompass-api:latest
            sudo docker run -d --name jobcompass-api -p 3000:3000 --env-file .env ${{ secrets.DOCKER_USERNAME }}/jobcompass-api:latest
          EOF
