export enum Experience {
    ONE_TO_TWO_YEARS = '1-2_YEARS',
    TWO_TO_THREE_YEARS = '2-3_YEARS',
    FOUR_TO_FIVE_YEARS = '3-4_YEARS',
    FIVE_PLUS_YEARS = '5+_YEARS',
}

export enum Education {
    HIGH_SCHOOL = 'HIGH_SCHOOL',
    INTERMEDIATE = 'INTERMEDIATE',
    GRADUATION = 'GRADUATION',
    MASTER_DEGREE = 'MASTER_DEGREE',
    BACHELOR_DEGREE = 'BACHELOR_DEGREE',
}
